mysql:
  host: $MYSQL_HOST_IP
  port: $MYSQL_HOST_PORT
  dbname: $MYSQL_DB_NAME
  user: $MYSQL_DB_USER
  password: $MYSQL_DB_PWD
  number_of_connections: $MYSQL_CON_NUM

redis:
  host: $REDIS_HOST_IP
  port: $REDIS_HOST_PORT
  db: $REDIS_DB_NAME
  user: $REDIS_DB_USER
  password: $REDIS_DB_PWD
  number_of_connections: $REDIS_CON_NUM

threadpool:
  min: $THREADPOOL_MIN_SIZE
  max: $THREADPOOL_MAX_SIZE
  idletime: $THREADPOOL_IDLE_TIME
